import type { ThemeDefinition, ThemeId } from "@/types";

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  NORDIC_MINIMAL: {
    id: "NORDIC_MINIMAL",
    name: "Nordic Minimal",
    nameFa: "نوردیک مینیمال",
    description: "بافت ماسه‌سنگ و کتان گرم، تایپوگرافی آبسیدین و رنگ فندقی برشته — کافه‌های تخصصی مدرن و روشن",
    preview: {
      bg: "#F6F3EE",
      surface: "#FAF8F5",
      text: "#1C1917",
      accent: "#8B5E3C",
      border: "#DED7CA",
    },
    cssVars: {
      "--theme-bg": "#F6F3EE",
      "--theme-bg-2": "#ECE7DE",
      "--theme-surface": "#FAF8F5",
      "--theme-border": "#DED7CA",
      "--theme-text": "#1C1917",
      "--theme-text-2": "#78716C",
      "--theme-accent": "#8B5E3C",
      "--theme-accent-fg": "#FFFFFF",
      "--theme-accent-2": "#A2734E",
      "--theme-card-shadow": "0 2px 10px rgba(44,30,20,0.06)",
      "--theme-card-shadow-hover": "0 6px 20px rgba(44,30,20,0.12)",
      "--theme-card-shadow-lg": "0 12px 32px rgba(44,30,20,0.16)",
      "--theme-radius-sm": "6px",
      "--theme-radius": "12px",
      "--theme-radius-lg": "20px",
      "--theme-radius-full": "9999px",
      "--theme-font-weight-display": "800",
      "--theme-accent-glow": "rgba(139, 94, 60, 0.25)",
    },
  },
  OLED_CARBON: {
    id: "OLED_CARBON",
    name: "OLED Carbon",
    nameFa: "اولد کربن",
    description: "مشکی ژرف OLED، سطوح کربنی و طلایی کهربایی درخشان — بارهای تخصصی شبانه و محیط‌های دارک",
    preview: {
      bg: "#080808",
      surface: "#181818",
      text: "#F5F5F4",
      accent: "#F59E0B",
      border: "#282828",
    },
    cssVars: {
      "--theme-bg": "#080808",
      "--theme-bg-2": "#121212",
      "--theme-surface": "#181818",
      "--theme-border": "#282828",
      "--theme-text": "#F5F5F4",
      "--theme-text-2": "#A8A29E",
      "--theme-accent": "#F59E0B",
      "--theme-accent-fg": "#080808",
      "--theme-accent-2": "#D97706",
      "--theme-card-shadow": "0 4px 20px rgba(0,0,0,0.8)",
      "--theme-card-shadow-hover": "0 6px 24px rgba(0,0,0,0.95)",
      "--theme-card-shadow-lg": "0 16px 40px rgba(0,0,0,0.98)",
      "--theme-radius-sm": "6px",
      "--theme-radius": "10px",
      "--theme-radius-lg": "18px",
      "--theme-radius-full": "9999px",
      "--theme-font-weight-display": "900",
      "--theme-accent-glow": "rgba(245, 158, 11, 0.45)",
    },
  },
  ARTISAN_SEPIA: {
    id: "ARTISAN_SEPIA",
    name: "Artisan Sepia",
    nameFa: "آرتیزان سپیا",
    description: "کرم کاغذ دست‌ساز، خطوط ظریف و قهوه‌ای برشته سنتی — روستری‌ها و کافه‌عمارت‌های اصیل",
    preview: {
      bg: "#F8F3E8",
      surface: "#FFFDF9",
      text: "#2B1D14",
      accent: "#8D4A23",
      border: "#DFCDB8",
    },
    cssVars: {
      "--theme-bg": "#F8F3E8",
      "--theme-bg-2": "#EFE6D5",
      "--theme-surface": "#FFFDF9",
      "--theme-border": "#DFCDB8",
      "--theme-text": "#2B1D14",
      "--theme-text-2": "#745846",
      "--theme-accent": "#8D4A23",
      "--theme-accent-fg": "#FFFDF9",
      "--theme-accent-2": "#A85B2D",
      "--theme-card-shadow": "0 2px 8px rgba(43,29,20,0.08)",
      "--theme-card-shadow-hover": "0 6px 18px rgba(43,29,20,0.14)",
      "--theme-card-shadow-lg": "0 12px 30px rgba(43,29,20,0.18)",
      "--theme-radius-sm": "4px",
      "--theme-radius": "8px",
      "--theme-radius-lg": "16px",
      "--theme-radius-full": "9999px",
      "--theme-font-weight-display": "800",
      "--theme-accent-glow": "rgba(141, 74, 35, 0.3)",
    },
  },
  NEO_EDITORIAL: {
    id: "NEO_EDITORIAL",
    name: "Neo Editorial",
    nameFa: "نئو ادیتوریال",
    description: "گرید فریم مشکی شارپ، سایه‌های بلوکی و تایپوگرافی روزنامه‌ای — کافه‌های مینیمال آرت و ژورنال",
    preview: {
      bg: "#F4F4F0",
      surface: "#FFFFFF",
      text: "#09090B",
      accent: "#09090B",
      border: "#18181B",
    },
    cssVars: {
      "--theme-bg": "#F4F4F0",
      "--theme-bg-2": "#E8E8E2",
      "--theme-surface": "#FFFFFF",
      "--theme-border": "#18181B",
      "--theme-text": "#09090B",
      "--theme-text-2": "#52525B",
      "--theme-accent": "#18181B",
      "--theme-accent-fg": "#FFFFFF",
      "--theme-accent-2": "#3F3F46",
      "--theme-card-shadow": "4px 4px 0px #18181B",
      "--theme-card-shadow-hover": "6px 6px 0px #18181B",
      "--theme-card-shadow-lg": "8px 8px 0px #18181B",
      "--theme-radius-sm": "0px",
      "--theme-radius": "0px",
      "--theme-radius-lg": "0px",
      "--theme-radius-full": "0px",
      "--theme-font-weight-display": "900",
      "--theme-accent-glow": "none",
    },
  },
  WARM_TERRACOTTA: {
    id: "WARM_TERRACOTTA",
    name: "Warm Terracotta",
    nameFa: "ترراکوتای گرم",
    description: "تنالیته خاکی و سفالی گرم، با انحناهای نرم و دعوت‌کننده — بیکری‌ها، قنادی‌ها و فضاهای برانچ",
    preview: {
      bg: "#FCF3EC",
      surface: "#FFFFFF",
      text: "#3C1B10",
      accent: "#C25327",
      border: "#F3D2C0",
    },
    cssVars: {
      "--theme-bg": "#FCF3EC",
      "--theme-bg-2": "#F7E4D8",
      "--theme-surface": "#FFFFFF",
      "--theme-border": "#F3D2C0",
      "--theme-text": "#3C1B10",
      "--theme-text-2": "#8C513D",
      "--theme-accent": "#C25327",
      "--theme-accent-fg": "#FCF3EC",
      "--theme-accent-2": "#D96B40",
      "--theme-card-shadow": "0 4px 16px rgba(194,83,39,0.12)",
      "--theme-card-shadow-hover": "0 8px 24px rgba(194,83,39,0.20)",
      "--theme-card-shadow-lg": "0 16px 36px rgba(194,83,39,0.24)",
      "--theme-radius-sm": "12px",
      "--theme-radius": "22px",
      "--theme-radius-lg": "30px",
      "--theme-radius-full": "9999px",
      "--theme-font-weight-display": "800",
      "--theme-accent-glow": "rgba(194, 83, 39, 0.35)",
    },
  },
};

export function getTheme(themeId?: string): ThemeDefinition {
  if (typeof themeId === "string" && Object.prototype.hasOwnProperty.call(THEMES, themeId)) {
    return THEMES[themeId as ThemeId];
  }
  return THEMES.NORDIC_MINIMAL;
}

export function getThemeCssString(themeId?: string | ThemeId): string {
  const theme = getTheme(themeId as string);
  return Object.entries(theme.cssVars)
    .map(([key, value]) => `${key}: ${value};`)
    .join(" ");
}

export const THEME_LIST = Object.values(THEMES);
